### ISSUE TITLE
Describe reconstruction of parses in the presence of the Leo optimization

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/Marpa--R2#288] opened 2022-12-03 21:53 UTC
@jeffreykegler mentioned that his description of how to analyze Leo chains might be too daunting.  Here's what I'm planning to do:

**Definition:** A *derivation path* is a sequence, in Earley set order, of predecessor Earley items of a completion, not including the completion, even if that completion was optimized out via Leo.

**Premise:**  In Earley set *k* we have a completion X = [A→𝜶B., *i*], where the origin of B is known to be *j*, but can find no completion for a rule B→𝜷 with origin *j* in the same Earley set.

This completion must have been optimized away by Leo.  To find all completions missing from set *k* that would otherwise contribute to X:

1. In set *k*, find a completion [C→𝜹., *m*] and a matching Leo item in set *m* of the form [A→𝜶B., C, *i*]
2. The unique item Y in set *m* of the form [D→𝜸.C, *h*] is the source of the Leo item found.
3. it is also the last element of all derivation paths participating in X that cover the range [*h*, *k*)
4. The corresponding **completion missing from set *k* is  [D→𝜸C., *h*]**
5. The derivation paths for any parent of Y  end with the unique item in set *h* of the form [E→𝝃.D, *g*]
6. go to step 2, substituting [E→𝝃.D, *g*] for [D→𝜸.C, *h*] and *h* for *m*, until you reach the tail of a derivation path for `X`

**Comment by jeffreykegler** [comment] 2022-12-09 23:31
The following file contains nothing new -- it is the same as in [my comment  above](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1339763285), except using the new Marpa::R2 diagnostic, so that there is more detail for the Leo items.

```
=== Progress @0 ===
P0 @0-0 L0c0 A -> . 'w' 'x' B
P1 @0-0 L0c0 A -> . 'w'
P5 @0-0 L0c0 :start -> . A
=== Progress @1 ===
R0:1 @0-1 L1c1 A -> 'w' . 'x' B
F1 @0-1 L1c1 A -> 'w' .
F5 @0-1 L1c1 :start -> A .
=== Progress @2 ===
R0:2 @0-2 L1c1-3 A -> 'w' 'x' . B
P2 @2-2 L1c3 B -> . C
P3 @2-2 L1c3 C -> . 'y' 'z' A
P4 @2-2 L1c3 C -> . 'y' 'z' 'w' 'x' 'y' 'z' 'w'
L2 [[A -> 'w' 'x' . B]; "B"; 0]
L2 [[A -> 'w' 'x' . B]; "C"; 2]
=== Progress @3 ===
R3:1 @2-3 L1c3-5 C -> 'y' . 'z' A
R4:1 @2-3 L1c3-5 C -> 'y' . 'z' 'w' 'x' 'y' 'z' 'w'
=== Progress @4 ===
P0 @4-4 L1c7 A -> . 'w' 'x' B
P1 @4-4 L1c7 A -> . 'w'
R3:2 @2-4 L1c3-7 C -> 'y' 'z' . A
R4:2 @2-4 L1c3-7 C -> 'y' 'z' . 'w' 'x' 'y' 'z' 'w'
L4 [[A -> 'w' 'x' . B]; "A"; 2]
=== Progress @5 ===
R0:1 @4-5 L1c7-9 A -> 'w' . 'x' B
F0 @0-5 L1c1-9 A -> 'w' 'x' B .
F1 @4-5 L1c7-9 A -> 'w' .
F2 @2-5 L1c3-9 B -> C .
F3 @2-5 L1c3-9 C -> 'y' 'z' A .
R4:3 @2-5 L1c3-9 C -> 'y' 'z' 'w' . 'x' 'y' 'z' 'w'
F5 @0-5 L1c1-9 :start -> A .
=== Progress @6 ===
R0:2 @4-6 L1c7-11 A -> 'w' 'x' . B
P2 @6-6 L1c11 B -> . C
P3 @6-6 L1c11 C -> . 'y' 'z' A
P4 @6-6 L1c11 C -> . 'y' 'z' 'w' 'x' 'y' 'z' 'w'
R4:4 @2-6 L1c3-11 C -> 'y' 'z' 'w' 'x' . 'y' 'z' 'w'
L6 [[A -> 'w' 'x' . B]; "B"; 4]
L6 [[A -> 'w' 'x' . B]; "C"; 6]
=== Progress @7 ===
R3:1 @6-7 L1c11-13 C -> 'y' . 'z' A
R4:1 @6-7 L1c11-13 C -> 'y' . 'z' 'w' 'x' 'y' 'z' 'w'
R4:5 @2-7 L1c3-13 C -> 'y' 'z' 'w' 'x' 'y' . 'z' 'w'
=== Progress @8 ===
P0 @8-8 L1c15 A -> . 'w' 'x' B
P1 @8-8 L1c15 A -> . 'w'
R3:2 @6-8 L1c11-15 C -> 'y' 'z' . A
R4:2 @6-8 L1c11-15 C -> 'y' 'z' . 'w' 'x' 'y' 'z' 'w'
R4:6 @2-8 L1c3-15 C -> 'y' 'z' 'w' 'x' 'y' 'z' . 'w'
L8 [[A -> 'w' 'x' . B]; "A"; 6]
=== Progress @9 ===
R0:1 @8-9 L1c15-17 A -> 'w' . 'x' B
F0 x2 @0,4-9 L1c1-17 A -> 'w' 'x' B .
F1 @8-9 L1c15-17 A -> 'w' .
F2 x2 @2,6-9 L1c3-17 B -> C .
F3 x2 @2,6-9 L1c3-17 C -> 'y' 'z' A .
R4:3 @6-9 L1c11-17 C -> 'y' 'z' 'w' . 'x' 'y' 'z' 'w'
F4 @2-9 L1c3-17 C -> 'y' 'z' 'w' 'x' 'y' 'z' 'w' .
F5 @0-9 L1c1-17 :start -> A .
```

**Comment by jeffreykegler** [comment] 2022-12-09 23:32
@dabrahams, if I remember correctly, with the completion of my Marpa::R2 Leo diagnostics, we are done with this issue.  Absent feedback to the contrary, I will close this issue in a couple of days.

**Comment by dabrahams** [comment] 2022-12-10 02:04
Sure, this one should be closed, but don't you want another for the paper, with the original topic?

**Comment by jeffreykegler** [comment] 2022-12-10 17:03
I made the changes in the paper repo already.  The issue is https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11.  Please report any problems with the changed version under that issue, or in a new issue in the [arxiv paper repo](https://github.com/jeffreykegler/Marpa-arxiv-paper).
 
For your convenience, I've uploaded a PDF of the revised paper: https://drive.google.com/file/d/1_2AmXs6PhEqDNe8gAeaolps6HKT1nrsq/view?usp=sharing .  The revisions are mainly in sections 5 and 6.  If you are interested in looking at it, please download it in the next couple of days, as I regularly clean up that Google Drive directory.

Per [your comment](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1344978200), I will close this issue after a couple of days, unless something comes up.

**Comment by jeffreykegler** [comment] 2022-12-10 21:36
I made the changes in the paper repo already.  The issue is https://github.com/jeffreykegler/Marpa-arxiv-paper/issues/11.  Please report any problems with the changed version under that issue, or in a new issue in the [arxiv paper repo](https://github.com/jeffreykegler/Marpa-arxiv-paper).
 
For your convenience, I've uploaded a PDF of the revised paper: https://drive.google.com/file/d/1_2AmXs6PhEqDNe8gAeaolps6HKT1nrsq/view?usp=sharing .  The revisions are mainly in sections 5 and 6.  If you are interested in looking at it, please download it in the next couple of days, as I regularly clean up that Google Drive directory.

Per [your comment](https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1344978200), I will close this issue after a couple of days, unless something comes up.

**Comment by jeffreykegler** [comment] 2022-12-15 16:33
Per https://github.com/jeffreykegler/Marpa--R2/issues/288#issuecomment-1345326259, I am closing this issue.

**Closed by jeffreykegler** 2022-12-15 16:33 UTC
Labels: About to be closed

**Comment by dabrahams** [comment] 2022-12-17 19:37
I believe I found a case for which my logic fails.  Consider this similar grammar with the same input:

```ebnf
      A ::= 'w' 'x' B | 'w'
      B ::= 'y' 'z' 'w' 'x' 'y' 'z' 'w'
      B ::= 'y' 'z' A
```

for which I get the following chart:

```
---------- 0 ----------
0: [0 A	::= [0 •'w' 'x' B
1: [0 A	::= [0 •'w'
---------- 1 ----------
2: [0 A	::= [0  'w' 1]	•'x' B
3: [0 A 1]	::= [0  'w' 1]	•
---------- 2 ----------
4: [0 A]	::= [0 'w' 'x' {2} B•B*
5: [0 A	::= [0 'w' {1} 'x' 2]	•B
6: [2 B	::= [2 •'y' 'z' 'w' 'x' 'y' 'z' 'w'
7: [2 B	::= [2 •'y' 'z' A
---------- 3 ----------
8: [2 B	::= [2  'y' 3]	•'z' 'w' 'x' 'y' 'z' 'w'
9: [2 B	::= [2  'y' 3]	•'z' A
---------- 4 ----------
10: [0 A]	::= [0 'w' 'x' {2} B•A*
11: [2 B	::= [2 'y' {3} 'z' 4]	•A
12: [2 B	::= [2 'y' {3} 'z' 4]	•'w' 'x' 'y' 'z' 'w'
13: [4 A	::= [4 •'w' 'x' B
14: [4 A	::= [4 •'w'
---------- 5 ----------
15: [2 B	::= [2 'y' 'z' {4} 'w' 5]	•'x' 'y' 'z' 'w'
16: [4 A	::= [4  'w' 5]	•'x' B
17: [0 A 5]	::= [0 'w' 'x' {2} B 5]	•
18: [4 A 5]	::= [4  'w' 5]	•
---------- 6 ----------
19: [0 A]	::= [0 'w' 'x' {2} B•B*
20: [4 A	::= [4 'w' {5} 'x' 6]	•B
21: [2 B	::= [2 'y' 'z' 'w' {5} 'x' 6]	•'y' 'z' 'w'
22: [6 B	::= [6 •'y' 'z' 'w' 'x' 'y' 'z' 'w'
23: [6 B	::= [6 •'y' 'z' A
---------- 7 ----------
24: [2 B	::= [2 'y' 'z' 'w' 'x' {6} 'y' 7]	•'z' 'w'
25: [6 B	::= [6  'y' 7]	•'z' 'w' 'x' 'y' 'z' 'w'
26: [6 B	::= [6  'y' 7]	•'z' A
---------- 8 ----------
27: [0 A]	::= [0 'w' 'x' {2} B•A*
28: [6 B	::= [6 'y' {7} 'z' 8]	•A
29: [2 B	::= [2 'y' 'z' 'w' 'x' 'y' {7} 'z' 8]	•'w'
30: [6 B	::= [6 'y' {7} 'z' 8]	•'w' 'x' 'y' 'z' 'w'
31: [8 A	::= [8 •'w' 'x' B
32: [8 A	::= [8 •'w'
---------- 9 ----------
33: [6 B	::= [6 'y' 'z' {8} 'w' 9]	•'x' 'y' 'z' 'w'
34: [8 A	::= [8  'w' 9]	•'x' B
35: [2 B 9]	::= [2 'y' 'z' 'w' 'x' 'y' 'z' {8} 'w' 9]	•
36: [0 A 9]	::= [0 'w' 'x' {2} B 9]	•
37: [8 A 9]	::= [8  'w' 9]	•
---------- 10 ----------

Set:  0     1     2     3     4     5     6     7     8     9
A ::=   'w'   'x'    B....................................
      0     2     5                                        36
B ::=               'y'   'z'    A........................
                  7     9     11
B ::=               'y'   'z'   'w'   'x'   'y'   'z'   'w'
                  6     8     12    15   21    21    29    35
A ::=                           'w'   'x'    B............
                              13    16   20
B ::=                                       'y'   'z'   A
                                         23    26    28
A ::=                                                  'w'
                                                     32    37
```

Item 36 (the completion of A over 2-9) is derived two ways:
1. By combining Earley 5 with Earley completion 35
2. By combining Leo item 27 with completion 37

Since there is a perfectly legitimate completion of B covering sets 2-9 (item 35), nothing would cause my earlier-stated procedure to consider reconstructing the Leo-eliminated completion of the derivation path for B made of items 7, 9, and 11.

It seems that in general, any completion that's actually found in the chart could have arisen in either way.  I think I can adjust to account for this fact and will post an update here when I've thought the problem through.
